# Generated by Django 5.0.6 on 2024-05-11 03:56

import autoslug.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=100, verbose_name='Publisher Name')),
                ('publisher_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='publisher_name')),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, verbose_name='App Name')),
                ('app_icon', models.URLField(default=None, verbose_name='App Icon')),
                ('app_header_image', models.URLField(default='', verbose_name='Header Image')),
                ('app_package_name', models.CharField(max_length=100, unique=True, verbose_name='Package Name')),
                ('package_category', models.JSONField(default=list, verbose_name='App Category')),
                ('app_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('app_downloads', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Downloads')),
                ('app_description', models.TextField(verbose_name='App Description')),
                ('app_updated_on', models.DateField(auto_now=True, verbose_name='Updated On')),
                ('app_version', models.CharField(default=None, max_length=50, verbose_name='App Version')),
                ('app_screenshots', models.JSONField(default=list, verbose_name='App Screenshots')),
                ('app_summary', models.TextField(default=None, verbose_name='App Summary')),
                ('app_permissions', models.JSONField(default=dict, verbose_name='App Permissions')),
                ('app_reviews_histogram', models.JSONField(default=list, verbose_name='App Histogram')),
                ('publisher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.publisher', verbose_name='Publisher Name')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
            },
        ),
    ]
