# Generated by Django 5.0.3 on 2024-03-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0003_alter_apps_app_screenshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='package_category',
            field=models.CharField(choices=[('app', 'App'), ('game', 'Game')], default=('app', 'App'), max_length=50, verbose_name='Package Category'),
        ),
    ]
