# Generated by Django 5.0.3 on 2024-03-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0004_apps_package_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='package_category',
            field=models.CharField(choices=[('app', 'App'), ('game', 'Game'), ('none', 'Undefined')], default=('none', 'Undefined'), max_length=50, verbose_name='Package Category'),
        ),
    ]
