# Generated by Django 5.0.3 on 2024-03-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0006_remove_apps_app_screenshots_apps_screenshot_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='screenshot_1',
            field=models.ImageField(default=None, upload_to=None, verbose_name='Screenshot 1'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='screenshot_2',
            field=models.ImageField(default=None, upload_to=None, verbose_name='Screenshot 2'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='screenshot_3',
            field=models.ImageField(default=None, upload_to=None, verbose_name='Screenshot 3'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='screenshot_4',
            field=models.ImageField(default=None, upload_to=None, verbose_name='Screenshot 4'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='screenshot_5',
            field=models.ImageField(default=None, upload_to=None, verbose_name='Screenshot 5'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='screenshot_6',
            field=models.ImageField(default=None, upload_to=None, verbose_name='Screenshot 6'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='screenshot_7',
            field=models.ImageField(default=None, upload_to=None, verbose_name='Screenshot 7'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='screenshot_8',
            field=models.ImageField(default=None, upload_to=None, verbose_name='Screenshot 8'),
        ),
    ]
