# Generated by Django 5.0.3 on 2024-03-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0007_alter_apps_screenshot_1_alter_apps_screenshot_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='screenshot_1',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='screenshot_2',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='screenshot_3',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='screenshot_4',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='screenshot_5',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='screenshot_6',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='screenshot_7',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='screenshot_8',
        ),
        migrations.AddField(
            model_name='apps',
            name='app_header_image',
            field=models.URLField(default='', verbose_name='Header Image'),
        ),
        migrations.AddField(
            model_name='apps',
            name='app_icon',
            field=models.URLField(default=None, verbose_name='App Icon'),
        ),
        migrations.AddField(
            model_name='apps',
            name='app_screenshots',
            field=models.JSONField(default=list, verbose_name='App Screenshots'),
        ),
        migrations.AddField(
            model_name='apps',
            name='app_summary',
            field=models.TextField(default=None, verbose_name='App Summary'),
        ),
        migrations.AddField(
            model_name='apps',
            name='app_version',
            field=models.CharField(default=None, max_length=50, verbose_name='App Version'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='package_category',
            field=models.JSONField(default=list, verbose_name='App Category'),
        ),
    ]
