# Generated by Django 5.0.3 on 2024-03-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0008_remove_apps_screenshot_1_remove_apps_screenshot_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='app_permissions',
            field=models.JSONField(default=dict, verbose_name='App Permissions'),
        ),
    ]
