# Generated by Django 5.0.3 on 2024-03-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0009_apps_app_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='app_reviews_histogram',
            field=models.JSONField(default=list, verbose_name='App Histogram'),
        ),
    ]
